[profile.release]
panic = 'unwind'

[workspace]
members = [
    'echoServer',
    'tcpServer',
    'clitools',
    'substrate-node/node',
    'substrate-node/runtime',
    'substrate-node/pallets/template',
    'substrate-node/pallets/erc20',
    'substrate-node/pallets/evidence'
]
