[package]
name = "clitools"
version = "0.1.0"
authors = ["Vz <Vincent.Zou@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version="0.3.16", features = [ "paw" ] }
paw = "1.0"